export const EVENT_SYNC_COOKIE: SyncCookie.SyncCookieEventKey = 'EVENT_SYNC_COOKIE'
export const STORAGE_SYNC_COOKIE_RELATIONS: SyncCookie.StorageKey = 'STORAGE_SYNC_COOKIE_RELATIONS'


export const EVENT_DISGUISE_REQUEST: DisguiseRequest.DisguiseRequestEventKey = 'EVENT_DISGUISE_REQUEST'
export const STORAGE_DISGUISE_REQUEST_RELATIONS: DisguiseRequest.StorageKey = 'STORAGE_DISGUISE_REQUEST_RELATIONS'
