export enum RUN_TIME_EVENT {
  OPEN_WORKBENCH = 'OPEN_WORKBENCH',
  SYNC_COOKIE = 'SYNC_COOKIE',
  DISGUISE_REQUEST = 'DISGUISE_REQUEST',
  GROUP_TABS = 'GROUP_TABS',
  UNGROUP_TABS = 'UNGROUP_TABS',
  CHANGE_GROUP_TABS = 'CHANGE_GROUP_TABS',
}

export enum STORAGE_KEY {
  SYNC_COOKIE_RELATIONS = 'SYNC_COOKIE_RELATIONS',
  DISGUISE_REQUEST_RELATIONS = 'DISGUISE_REQUEST_RELATIONS',
}
