export enum RUN_TIME_EVENT {
  SYNC_COOKIE = 'SYNC_COOKIE',
  DISGUISE_REQUEST = 'DISGUISE_REQUEST',
}

export enum STORAGE_KEY {
  SYNC_COOKIE_RELATIONS = 'SYNC_COOKIE_RELATIONS',
  DISGUISE_REQUEST_RELATIONS = 'DISGUISE_REQUEST_RELATIONS',
}
